//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.OFMISEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Offices = new HashSet<Office>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string ExtName { get; set; }
        public string Position { get; set; }
        public string OfficeName { get; set; }
        public string OffcAcr { get; set; }
        public Nullable<int> OfficeId { get; set; }
        public string TIN { get; set; }
        public string PagIbig { get; set; }
        public string PhilHealth { get; set; }
        public string SSS { get; set; }
        public string Status { get; set; }
        public string Salutation { get; set; }
        public string SG { get; set; }
        public string GSIS { get; set; }
        public string SalaryGrade { get; set; }
        public string Steps { get; set; }
        public Nullable<decimal> MonthlySalary { get; set; }
        public Nullable<decimal> DailySalary { get; set; }
        public Nullable<bool> IsHead { get; set; }
        public Nullable<bool> IsSignatories { get; set; }
        public string Note { get; set; }
        public string EmployeeNameByLastName { get; set; }
        public string EmployeeName { get; set; }
        public string LBPAccount { get; set; }
        public bool Deactivate { get; set; }
    
        public virtual Office Office { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Office> Offices { get; set; }
    }
}
