//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.HRMISEntites
{
    using System;
    using System.Collections.Generic;
    
    public partial class Office
    {
        public string fldOfficeID { get; set; }
        public string fldOfficeName { get; set; }
        public string fldChief { get; set; }
        public string fldTelNo { get; set; }
        public int fldIndex { get; set; }
        public string fldSequence { get; set; }
        public string fldMainOffice { get; set; }
        public Nullable<bool> fldOldNew { get; set; }
        public Nullable<long> fldEmpID { get; set; }
        public Nullable<long> fldAOEmpID { get; set; }
    }
}
