// <auto-generated />
namespace Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class AddUsersInPR : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddUsersInPR));
        
        string IMigrationMetadata.Id
        {
            get { return "202411101026539_AddUsersInPR"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
