//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICTMigration.ICTv2Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActionLog
    {
        public int Id { get; set; }
        public string CreatedBy { get; set; }
        public string NewValue { get; set; }
        public string OldValue { get; set; }
        public string ModifyType { get; set; }
        public Nullable<int> ActionId { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public string ModifiedBy { get; set; }
    }
}
