//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICTMigration.ICTv2Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerActionSheet
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string OfficeAddress { get; set; }
        public string Name { get; set; }
        public string ContactNo { get; set; }
        public string PositionWork { get; set; }
        public string Gender { get; set; }
        public string ClientRequest { get; set; }
        public string ActionTaken { get; set; }
        public string AssistedBy { get; set; }
        public Nullable<bool> IsDone { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string CreatedBy { get; set; }
    }
}
