//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICTMigration.ICTv2Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveriesICTSpec
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DeliveriesICTSpec()
        {
            this.DeliveriesICTSpecsDetails = new HashSet<DeliveriesICTSpecsDetail>();
            this.DeliveriesActualDeliveries = new HashSet<DeliveriesActualDelivery>();
            this.DeliveriesPOes = new HashSet<DeliveriesPO>();
            this.DeliveriesQuotations = new HashSet<DeliveriesQuotation>();
        }
    
        public int Id { get; set; }
        public Nullable<int> DeliveryId { get; set; }
        public Nullable<int> ItemOrder { get; set; }
        public Nullable<int> ItemNo { get; set; }
        public Nullable<int> ICTSpecsId { get; set; }
        public string Description { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> BrandId { get; set; }
        public Nullable<int> ModelId { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public string Unit { get; set; }
        public Nullable<decimal> UnitCost { get; set; }
        public Nullable<decimal> TotalCost { get; set; }
        public Nullable<decimal> ProposedBudget { get; set; }
        public string Purpose { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> TicketReqICTSpecsId { get; set; }
        public string SerialNo { get; set; }
    
        public virtual Delivery Delivery { get; set; }
        public virtual TicketEquipmentBrand TicketEquipmentBrand { get; set; }
        public virtual TicketEquipmentModel TicketEquipmentModel { get; set; }
        public virtual TicketICTSpec TicketICTSpec { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeliveriesICTSpecsDetail> DeliveriesICTSpecsDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeliveriesActualDelivery> DeliveriesActualDeliveries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeliveriesPO> DeliveriesPOes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeliveriesQuotation> DeliveriesQuotations { get; set; }
    }
}
