//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICTMigration.ICTv2Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ICTv2Entities : DbContext
    {
        public ICTv2Entities()
            : base("name=ICTv2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActionList> ActionLists { get; set; }
        public virtual DbSet<Action> Actions { get; set; }
        public virtual DbSet<Article> Articles { get; set; }
        public virtual DbSet<CustomerActionSheet> CustomerActionSheets { get; set; }
        public virtual DbSet<Delivery> Deliveries { get; set; }
        public virtual DbSet<DeliveriesICTSpec> DeliveriesICTSpecs { get; set; }
        public virtual DbSet<DeliveriesICTSpecsDetail> DeliveriesICTSpecsDetails { get; set; }
        public virtual DbSet<DocAction> DocActions { get; set; }
        public virtual DbSet<Document> Documents { get; set; }
        public virtual DbSet<Dropdown> Dropdowns { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<EquipmentProblem> EquipmentProblems { get; set; }
        public virtual DbSet<EquipmentProfile> EquipmentProfiles { get; set; }
        public virtual DbSet<EquipmentType> EquipmentTypes { get; set; }
        public virtual DbSet<EvaluationSheet> EvaluationSheets { get; set; }
        public virtual DbSet<EvaluationSheet1> EvaluationSheets1 { get; set; }
        public virtual DbSet<Log> Logs { get; set; }
        public virtual DbSet<ME> MES { get; set; }
        public virtual DbSet<Office> Offices { get; set; }
        public virtual DbSet<PGNAccountHistory> PGNAccountHistories { get; set; }
        public virtual DbSet<PGNAccount> PGNAccounts { get; set; }
        public virtual DbSet<PGNAcc> PGNAccs { get; set; }
        public virtual DbSet<PGNActivity> PGNActivities { get; set; }
        public virtual DbSet<PGNMacAdderess> PGNMacAdderesses { get; set; }
        public virtual DbSet<PGNNonEmployee> PGNNonEmployees { get; set; }
        public virtual DbSet<PGNRequest> PGNRequests { get; set; }
        public virtual DbSet<PGNRequestAccount> PGNRequestAccounts { get; set; }
        public virtual DbSet<PGNRequestImage> PGNRequestImages { get; set; }
        public virtual DbSet<PGNRequestStatu> PGNRequestStatus { get; set; }
        public virtual DbSet<PGN> PGNs { get; set; }
        public virtual DbSet<PITDService> PITDServices { get; set; }
        public virtual DbSet<PPELog> PPELogs { get; set; }
        public virtual DbSet<PPE> PPEs { get; set; }
        public virtual DbSet<PPEsNew> PPEsNews { get; set; }
        public virtual DbSet<PPEsNewSpec> PPEsNewSpecs { get; set; }
        public virtual DbSet<PREquipment> PREquipments { get; set; }
        public virtual DbSet<Province> Provinces { get; set; }
        public virtual DbSet<PRStandardQuarter> PRStandardQuarters { get; set; }
        public virtual DbSet<PurchaseOrder> PurchaseOrders { get; set; }
        public virtual DbSet<PurchaseReq> PurchaseReqs { get; set; }
        public virtual DbSet<PurchaseReqStandardEquipment> PurchaseReqStandardEquipments { get; set; }
        public virtual DbSet<Remark> Remarks { get; set; }
        public virtual DbSet<Repair> Repairs { get; set; }
        public virtual DbSet<Setting> Settings { get; set; }
        public virtual DbSet<SophosPGNAccount> SophosPGNAccounts { get; set; }
        public virtual DbSet<StandardPRSpec> StandardPRSpecs { get; set; }
        public virtual DbSet<Status> Statuses { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tblBarangay> tblBarangays { get; set; }
        public virtual DbSet<tblFWTUActivity> tblFWTUActivities { get; set; }
        public virtual DbSet<tblFWTUActivityDropdown> tblFWTUActivityDropdowns { get; set; }
        public virtual DbSet<tblFWTUEquipmentInstallation> tblFWTUEquipmentInstallations { get; set; }
        public virtual DbSet<tblFWTUObservation> tblFWTUObservations { get; set; }
        public virtual DbSet<TechnicalEvaluationSheet> TechnicalEvaluationSheets { get; set; }
        public virtual DbSet<TechSpecEquipmentProfile> TechSpecEquipmentProfiles { get; set; }
        public virtual DbSet<TechSpecRequest> TechSpecRequests { get; set; }
        public virtual DbSet<TechSpec> TechSpecs { get; set; }
        public virtual DbSet<TechSpecsBasi> TechSpecsBasis { get; set; }
        public virtual DbSet<TechSpecsBasisDetail> TechSpecsBasisDetails { get; set; }
        public virtual DbSet<TechSpecsICTSpec> TechSpecsICTSpecs { get; set; }
        public virtual DbSet<TechSpecsICTSpecsDetail> TechSpecsICTSpecsDetails { get; set; }
        public virtual DbSet<TicketAction> TicketActions { get; set; }
        public virtual DbSet<TicketEquipment> TicketEquipments { get; set; }
        public virtual DbSet<TicketEquipmentBrand> TicketEquipmentBrands { get; set; }
        public virtual DbSet<TicketEquipmentModel> TicketEquipmentModels { get; set; }
        public virtual DbSet<TicketICTSpec> TicketICTSpecs { get; set; }
        public virtual DbSet<TicketICTSpecsDetail> TicketICTSpecsDetails { get; set; }
        public virtual DbSet<TicketReqDetail> TicketReqDetails { get; set; }
        public virtual DbSet<TicketReqICTSpec> TicketReqICTSpecs { get; set; }
        public virtual DbSet<TicketReqICTSpecsDetail> TicketReqICTSpecsDetails { get; set; }
        public virtual DbSet<TicketRequest> TicketRequests { get; set; }
        public virtual DbSet<TicketStatu> TicketStatus { get; set; }
        public virtual DbSet<TicketType> TicketTypes { get; set; }
        public virtual DbSet<Town> Towns { get; set; }
        public virtual DbSet<UnitType> UnitTypes { get; set; }
        public virtual DbSet<UserClaim> UserClaims { get; set; }
        public virtual DbSet<UserLogin> UserLogins { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<UserRolesInAction> UserRolesInActions { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<WorkOrder> WorkOrders { get; set; }
        public virtual DbSet<PGNAccsHistory> PGNAccsHistories { get; set; }
        public virtual DbSet<PGNAction> PGNActions { get; set; }
        public virtual DbSet<PGNDropdown> PGNDropdowns { get; set; }
        public virtual DbSet<PGNRequestAction> PGNRequestActions { get; set; }
        public virtual DbSet<PGNRequestIncomingType> PGNRequestIncomingTypes { get; set; }
        public virtual DbSet<Software> Softwares { get; set; }
        public virtual DbSet<SoftwareProfile> SoftwareProfiles { get; set; }
        public virtual DbSet<tblBarangayStaff> tblBarangayStaffs { get; set; }
        public virtual DbSet<tblBrgyPosition> tblBrgyPositions { get; set; }
        public virtual DbSet<tblFWSchedule> tblFWSchedules { get; set; }
        public virtual DbSet<tblTown> tblTowns { get; set; }
        public virtual DbSet<tblVisit> tblVisits { get; set; }
        public virtual DbSet<ActionLog> ActionLogs { get; set; }
        public virtual DbSet<DeliveriesActualDelivery> DeliveriesActualDeliveries { get; set; }
        public virtual DbSet<DeliveriesPO> DeliveriesPOes { get; set; }
        public virtual DbSet<DeliveriesQuotation> DeliveriesQuotations { get; set; }
    }
}
