//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICTMigration.ICTv2Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PGNAccount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PGNAccount()
        {
            this.PGNMacAdderesses = new HashSet<PGNMacAdderess>();
        }
    
        public int Id { get; set; }
        public Nullable<int> EmpId { get; set; }
        public string UserType { get; set; }
        public string UserName { get; set; }
        public string Status { get; set; }
        public Nullable<int> SigninCount { get; set; }
        public string TrafficSpeed { get; set; }
        public string Designation { get; set; }
        public string Remarks { get; set; }
        public string Office { get; set; }
        public string Password { get; set; }
        public Nullable<bool> NonEmployee { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PGNMacAdderess> PGNMacAdderesses { get; set; }
    }
}
