//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICTMigration.ICTv2Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PGNAccsHistory
    {
        public string UserName { get; set; }
        public string HistoryType { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string Remarks { get; set; }
        public string CreatedBy { get; set; }
    }
}
