//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICTMigration.ICTv2Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PGNAcc
    {
        public string UserName { get; set; }
        public string Type { get; set; }
        public string Status { get; set; }
        public Nullable<int> SignInCount { get; set; }
        public Nullable<int> TrafficSpeed { get; set; }
        public string TrafficDesc { get; set; }
        public string Designation { get; set; }
        public string Remarks { get; set; }
        public string Name { get; set; }
        public string AccGroup { get; set; }
        public string Password { get; set; }
        public string EmpStatus { get; set; }
        public string EmpPendingStatus { get; set; }
        public string EmpOldOffice { get; set; }
        public string fldFirstName { get; set; }
        public string fldMiddleName { get; set; }
        public string fldLastName { get; set; }
        public string fldNameExt { get; set; }
        public string MacAddresses { get; set; }
        public Nullable<int> fldHRISIdNo { get; set; }
    }
}
