//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICTMigration.ICTv2Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PGNDropdown
    {
        public Nullable<int> parentID { get; set; }
        public string category { get; set; }
        public string Value { get; set; }
        public Nullable<int> ddOrder { get; set; }
        public int Id { get; set; }
    }
}
