//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICTMigration.ICTv2Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PGNRequestImage
    {
        public int Id { get; set; }
        public Nullable<int> fldRequestId { get; set; }
        public string fldImagePath { get; set; }
        public Nullable<int> fldImagePage { get; set; }
    }
}
