//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICTMigration.ICTv2Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PGNRequest
    {
        public int Id { get; set; }
        public int RequestId { get; set; }
        public Nullable<System.DateTime> DateRequested { get; set; }
        public string SourceOffice { get; set; }
        public string SourceEmployee { get; set; }
        public string Subject { get; set; }
        public Nullable<int> ActivityId { get; set; }
        public Nullable<int> Deleted { get; set; }
        public Nullable<int> Completed { get; set; }
        public Nullable<int> CommType { get; set; }
        public string RequestBy { get; set; }
        public string fldEmpId { get; set; }
    }
}
