//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICTMigration.ICTv2Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PPE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PPE()
        {
            this.DocActions = new HashSet<DocAction>();
            this.EquipmentProfiles = new HashSet<EquipmentProfile>();
            this.WorkOrders = new HashSet<WorkOrder>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ArticleId { get; set; }
        public string PPEId { get; set; }
        public string Barcode { get; set; }
        public Nullable<int> OfficeId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public string PropertyNo { get; set; }
        public Nullable<int> EquipmentTypeId { get; set; }
        public string Description { get; set; }
        public string Serial { get; set; }
        public Nullable<System.DateTime> DateDelivered { get; set; }
        public Nullable<int> BoxNumber { get; set; }
        public Nullable<decimal> TotalCost { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocAction> DocActions { get; set; }
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquipmentProfile> EquipmentProfiles { get; set; }
        public virtual EquipmentType EquipmentType { get; set; }
        public virtual Office Office { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkOrder> WorkOrders { get; set; }
    }
}
