//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICTMigration.ICTv2Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PREquipment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PREquipment()
        {
            this.PurchaseReqStandardEquipments = new HashSet<PurchaseReqStandardEquipment>();
            this.StandardPRSpecs = new HashSet<StandardPRSpec>();
        }
    
        public int Id { get; set; }
        public Nullable<int> PRId { get; set; }
        public Nullable<int> ItemNo { get; set; }
        public Nullable<int> Quarter { get; set; }
        public string Description { get; set; }
        public string Remarks { get; set; }
        public string PRUrl { get; set; }
        public string Purpose { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> Unit { get; set; }
        public Nullable<decimal> UnitCost { get; set; }
        public Nullable<decimal> TotalCost { get; set; }
        public Nullable<int> EquipmentType { get; set; }
    
        public virtual PRStandardQuarter PRStandardQuarter { get; set; }
        public virtual PurchaseReq PurchaseReq { get; set; }
        public virtual TicketICTSpec TicketICTSpec { get; set; }
        public virtual UnitType UnitType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseReqStandardEquipment> PurchaseReqStandardEquipments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StandardPRSpec> StandardPRSpecs { get; set; }
    }
}
