//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICTMigration.ICTv2Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseReq
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PurchaseReq()
        {
            this.PREquipments = new HashSet<PREquipment>();
            this.PurchaseReqStandardEquipments = new HashSet<PurchaseReqStandardEquipment>();
            this.Deliveries = new HashSet<Delivery>();
        }
    
        public int Id { get; set; }
        public string PRNo { get; set; }
        public Nullable<int> TechSpecsId { get; set; }
        public Nullable<System.DateTime> DateRequested { get; set; }
        public string RequestedByOfficeId { get; set; }
        public string RequestedByDivision { get; set; }
        public Nullable<long> RequestedByChiefId { get; set; }
        public string RequestedByChiefName { get; set; }
        public string RequestedByChiefPos { get; set; }
        public Nullable<bool> IsDone { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<int> SpecificationType { get; set; }
        public string RequestedByName { get; set; }
        public Nullable<int> Quarter { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PREquipment> PREquipments { get; set; }
        public virtual PRStandardQuarter PRStandardQuarter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseReqStandardEquipment> PurchaseReqStandardEquipments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Delivery> Deliveries { get; set; }
    }
}
