//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICTMigration.ICTv2Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SophosPGNAccount
    {
        public int Id { get; set; }
        public string Username { get; set; }
        public string Fullname { get; set; }
        public string AccType { get; set; }
        public string AccStatus { get; set; }
        public Nullable<int> SignInCount { get; set; }
        public string TrafficShaping { get; set; }
        public string Category { get; set; }
        public string AccPassword { get; set; }
        public string Remarks { get; set; }
        public string Office { get; set; }
    }
}
