//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICTMigration.ICTv2Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBarangayStaff
    {
        public int Id { get; set; }
        public string fldName { get; set; }
        public Nullable<int> fldPositionId { get; set; }
        public Nullable<int> fldFocalPerson { get; set; }
        public string fldContactNo { get; set; }
        public Nullable<int> fldBarangayId { get; set; }
    }
}
