//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICTMigration.ICTv2Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBarangay
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblBarangay()
        {
            this.tblFWTUEquipmentInstallations = new HashSet<tblFWTUEquipmentInstallation>();
        }
    
        public int Id { get; set; }
        public string fldBarangayName { get; set; }
        public string fldBarangayAddress { get; set; }
        public Nullable<int> fldWithResolution { get; set; }
        public Nullable<int> fldTown { get; set; }
        public Nullable<int> fldOriented { get; set; }
        public Nullable<int> fldPhase { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblFWTUEquipmentInstallation> tblFWTUEquipmentInstallations { get; set; }
    }
}
