//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICTMigration.ICTv2Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFWTUEquipmentInstallation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblFWTUEquipmentInstallation()
        {
            this.tblFWTUActivities = new HashSet<tblFWTUActivity>();
        }
    
        public int Id { get; set; }
        public Nullable<int> BarangayId { get; set; }
        public Nullable<System.DateTime> InstallationDate { get; set; }
        public Nullable<bool> DataCabinet { get; set; }
        public string UPSSerial { get; set; }
        public string ModemSerial { get; set; }
        public string ModemLocation { get; set; }
        public string TelephoneSerial { get; set; }
        public string TelephoneNo { get; set; }
        public string TelephoneLoc { get; set; }
        public string AP1Serial { get; set; }
        public string AP2Serial { get; set; }
        public Nullable<int> BandwidthUp { get; set; }
        public Nullable<bool> Tarpaulin { get; set; }
        public Nullable<bool> MRF { get; set; }
        public string PreparedBy { get; set; }
        public string Status { get; set; }
        public Nullable<bool> Sticker { get; set; }
        public Nullable<int> BandwidthDown { get; set; }
    
        public virtual tblBarangay tblBarangay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblFWTUActivity> tblFWTUActivities { get; set; }
    }
}
