//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICTMigration.ICTv2Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFWSchedule
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> fldDate { get; set; }
        public Nullable<int> fldBarangayId { get; set; }
        public Nullable<int> fldVisitTypeId { get; set; }
    }
}
