//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICTMigration.ICTv2Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFWTUActivityDropdown
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblFWTUActivityDropdown()
        {
            this.tblFWTUObservations = new HashSet<tblFWTUObservation>();
        }
    
        public int Id { get; set; }
        public string Activity { get; set; }
        public string ActionsDone { get; set; }
        public Nullable<int> InstallationId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblFWTUObservation> tblFWTUObservations { get; set; }
    }
}
