//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICTMigration.ICTv2Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TechSpec
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TechSpec()
        {
            this.DocActions = new HashSet<DocAction>();
            this.EquipmentProfiles = new HashSet<EquipmentProfile>();
            this.TechSpecRequests = new HashSet<TechSpecRequest>();
            this.TechSpecsICTSpecs = new HashSet<TechSpecsICTSpec>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Requestedby { get; set; }
        public Nullable<int> EquipmentType { get; set; }
        public Nullable<decimal> Budget { get; set; }
        public string AssignedTo { get; set; }
        public string SpecType { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> DateApproved { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> DateRequested { get; set; }
        public string TableName { get; set; }
        public Nullable<int> WorOrderId { get; set; }
        public Nullable<bool> IsDone { get; set; }
        public Nullable<int> RequestId { get; set; }
        public Nullable<System.DateTime> DateAccepted { get; set; }
        public Nullable<long> RequestedById { get; set; }
        public string RequestedByName { get; set; }
        public string RequestedByPos { get; set; }
        public string RequestedByOfficeId { get; set; }
        public string RequestedByDivision { get; set; }
        public Nullable<long> RequestedByChiefId { get; set; }
        public string RequestedByChiefName { get; set; }
        public string RequestedByChiefPos { get; set; }
        public Nullable<bool> IsDivision { get; set; }
        public Nullable<bool> RequestBasedApprovedPR { get; set; }
        public Nullable<bool> RequestBasedApprovedAPP { get; set; }
        public Nullable<bool> RequestBasedApprovedAIP { get; set; }
        public Nullable<bool> RequestBasedApprovedPPMP { get; set; }
        public Nullable<bool> RequestBasedRequestLetter { get; set; }
        public string Gender { get; set; }
        public string ContactNo { get; set; }
        public Nullable<int> PreparedBy { get; set; }
        public string PreparedByName { get; set; }
        public string PreparedByPos { get; set; }
        public Nullable<int> ReviewedBy { get; set; }
        public string ReviewedByName { get; set; }
        public string ReviewedByPos { get; set; }
        public Nullable<int> NotedBy { get; set; }
        public string NotedByName { get; set; }
        public string NotedByPos { get; set; }
        public Nullable<bool> RequestedByForReplacement { get; set; }
        public Nullable<int> RepairId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocAction> DocActions { get; set; }
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquipmentProfile> EquipmentProfiles { get; set; }
        public virtual EquipmentType EquipmentType1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TechSpecRequest> TechSpecRequests { get; set; }
        public virtual TicketRequest TicketRequest { get; set; }
        public virtual User User { get; set; }
        public virtual WorkOrder WorkOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TechSpecsICTSpec> TechSpecsICTSpecs { get; set; }
    }
}
