//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICTMigration.ICTv2Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TechSpecsICTSpec
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TechSpecsICTSpec()
        {
            this.TechSpecsICTSpecsDetails = new HashSet<TechSpecsICTSpecsDetail>();
        }
    
        public int Id { get; set; }
        public Nullable<int> TechSpecsId { get; set; }
        public Nullable<int> ItemOrder { get; set; }
        public Nullable<int> ItemNo { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> ICTSpecsId { get; set; }
        public string Unit { get; set; }
        public Nullable<decimal> UnitCost { get; set; }
        public Nullable<decimal> TotalCost { get; set; }
        public string Purpose { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Description { get; set; }
        public string Equipment { get; set; }
    
        public virtual TechSpec TechSpec { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TechSpecsICTSpecsDetail> TechSpecsICTSpecsDetails { get; set; }
    }
}
