//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICTMigration.ICTv2Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketICTSpec
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TicketICTSpec()
        {
            this.DeliveriesICTSpecs = new HashSet<DeliveriesICTSpec>();
            this.PPEsNews = new HashSet<PPEsNew>();
            this.PREquipments = new HashSet<PREquipment>();
            this.TechSpecsBasis = new HashSet<TechSpecsBasi>();
            this.TicketEquipmentBrands = new HashSet<TicketEquipmentBrand>();
            this.TicketICTSpecsDetails = new HashSet<TicketICTSpecsDetail>();
            this.TicketReqICTSpecs = new HashSet<TicketReqICTSpec>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ItemNo { get; set; }
        public Nullable<int> EquipmentId { get; set; }
        public string Description { get; set; }
        public string Remarks { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeliveriesICTSpec> DeliveriesICTSpecs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PPEsNew> PPEsNews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PREquipment> PREquipments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TechSpecsBasi> TechSpecsBasis { get; set; }
        public virtual TicketEquipment TicketEquipment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TicketEquipmentBrand> TicketEquipmentBrands { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TicketICTSpecsDetail> TicketICTSpecsDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TicketReqICTSpec> TicketReqICTSpecs { get; set; }
    }
}
