//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICTMigration.ICTv2Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketReqDetail
    {
        public int Id { get; set; }
        public Nullable<int> RequestId { get; set; }
        public Nullable<int> ItemNo { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public string Unit { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> UnitCost { get; set; }
        public Nullable<decimal> TotalCost { get; set; }
        public string Item { get; set; }
        public Nullable<decimal> ProposedBudget { get; set; }
        public string Purpose { get; set; }
    
        public virtual TicketRequest TicketRequest { get; set; }
    }
}
