//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICTMigration.ICTv2Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketEquipmentBrand
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TicketEquipmentBrand()
        {
            this.DeliveriesICTSpecs = new HashSet<DeliveriesICTSpec>();
            this.PPEsNews = new HashSet<PPEsNew>();
            this.TicketEquipmentModels = new HashSet<TicketEquipmentModel>();
            this.TicketReqICTSpecs = new HashSet<TicketReqICTSpec>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ICTSpecsId { get; set; }
        public string Brand { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeliveriesICTSpec> DeliveriesICTSpecs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PPEsNew> PPEsNews { get; set; }
        public virtual TicketICTSpec TicketICTSpec { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TicketEquipmentModel> TicketEquipmentModels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TicketReqICTSpec> TicketReqICTSpecs { get; set; }
    }
}
