//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICTMigration.ICTv2Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketReqICTSpec
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TicketReqICTSpec()
        {
            this.TicketReqICTSpecsDetails = new HashSet<TicketReqICTSpecsDetail>();
        }
    
        public int Id { get; set; }
        public Nullable<int> RequestId { get; set; }
        public Nullable<int> ItemOrder { get; set; }
        public Nullable<int> ItemNo { get; set; }
        public Nullable<int> ICTSpecsId { get; set; }
        public string Description { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> BrandId { get; set; }
        public Nullable<int> ModelId { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public string Unit { get; set; }
        public Nullable<decimal> UnitCost { get; set; }
        public Nullable<decimal> TotalCost { get; set; }
        public Nullable<decimal> ProposedBudget { get; set; }
        public string Purpose { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string SerialNo { get; set; }
    
        public virtual TicketEquipmentBrand TicketEquipmentBrand { get; set; }
        public virtual TicketEquipmentModel TicketEquipmentModel { get; set; }
        public virtual TicketICTSpec TicketICTSpec { get; set; }
        public virtual TicketRequest TicketRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TicketReqICTSpecsDetail> TicketReqICTSpecsDetails { get; set; }
    }
}
