//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICTMigration.ICTv2Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketAction
    {
        public int Id { get; set; }
        public Nullable<int> RequestId { get; set; }
        public string ActionTakenBy { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> ActionDate { get; set; }
        public Nullable<int> StatusId { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<int> Completed { get; set; }
    
        public virtual TicketStatu TicketStatu { get; set; }
        public virtual TicketRequest TicketRequest { get; set; }
    }
}
