//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICTMigration.ICTv2Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WorkOrder()
        {
            this.DocActions = new HashSet<DocAction>();
            this.TechSpecs = new HashSet<TechSpec>();
        }
    
        public int Id { get; set; }
        public Nullable<int> PPEId { get; set; }
        public string WorkOrderId { get; set; }
        public Nullable<int> Box { get; set; }
        public Nullable<System.DateTime> RequestedDate { get; set; }
        public Nullable<int> RequestedBy { get; set; }
        public string Position { get; set; }
        public string Problem { get; set; }
        public string AssignedTo { get; set; }
        public string Findings { get; set; }
        public string Recommendation { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string FolderNo { get; set; }
        public Nullable<int> BoxNo { get; set; }
        public string CreatedBy { get; set; }
        public string DeliveredBy { get; set; }
        public string DeliveredDescription { get; set; }
        public Nullable<int> OfficeNo { get; set; }
        public Nullable<int> EquipmentTypeNo { get; set; }
        public Nullable<int> EquipmentCount { get; set; }
        public string SerialNumber { get; set; }
        public Nullable<bool> IsDone { get; set; }
        public Nullable<int> ValidatedBy { get; set; }
        public Nullable<int> NotedBy { get; set; }
        public Nullable<int> PreparedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocAction> DocActions { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual PPE PPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TechSpec> TechSpecs { get; set; }
        public virtual User User { get; set; }
    }
}
